### ISSUE TITLE
Remove IDs from the Video Screen and Add Course Name and Chapter Name instead

### ISSUE THREAD

**Issue by SudharakaP** [python-sinhala-education-society/OpenLearnr#154]
**Is your feature request related to a problem? Please describe.**

Currently in the Videos entity screen we display chapter and course IDs. 

![image](https://user-images.githubusercontent.com/12435965/67153692-b1048d00-f2a2-11e9-82b1-0a62371f9987.png)

So when the admin wants to know which chapter or course a video belongs to, he/she has to do a search on the relevant ID on the Chapter or Course entity screens. 

**Describe the solution you'd like**

Remove the ID columns as they are useless to the end user. Instead add `Course Name` and `Chapter Name` columns with hyperlinks to the relevant Course or Chapter itself.

**Comment by inspire99** [comment]
Hi @SudharakaP ,  I shall work on this.


Best Regards
Ganesh

**Comment by SudharakaP** [comment]
@inspire99 : Thanks for the contributions. 👍

**Comment by inspire99** [comment]
Hi @SudharakaP ,
I have created a pull request --> https://github.com/python-sinhala-education-society/OpenLearnr/pull/161

It contains changes to remove ID, and replace with name contents in video screen.

Regards
Ganesh

**Comment by SudharakaP** [comment]
@inspire99 : Wonderful. :smile: Thanks much for your time and work :smile:
