### ISSUE TITLE
Remove Couse ID from the Chapter Entity Screen and add Course Name Instead

### ISSUE THREAD

**Issue by SudharakaP** [python-sinhala-education-society/OpenLearnr#155]
**Is your feature request related to a problem? Please describe.**

Currently, Course ID is shown on the Chapter Entity Screen. 

![image](https://user-images.githubusercontent.com/12435965/67153733-5a4b8300-f2a3-11e9-859f-3fdd08fa112b.png)

This is useless to the end user. Instead we could remove the ID column and add `Course Name` instead with the names having a hyperlink to the relevant course.

**Comment by inspire99** [comment]
@SudharakaP : Hi.

As part of #hacktoberfest, would like to work on this. I have cloned it locally, will share updates.
Could you assign this issue to me?

Best Regards

**Comment by SudharakaP** [comment]
Yes we would appreciate if you could work on it. Feel free to open a pull
request.

**Comment by inspire99** [comment]
@SudharakaP , Related to #hacktoberfest, I would like to contribute.
Please check my pull request related to this issue --> https://github.com/python-sinhala-education-society/OpenLearnr/pull/156

Best Regards
Ganesh

**Comment by SudharakaP** [comment]
@inspire99 : Thanks much for your contribution. 

Btw, I noticed that you've used one GitHub account to do the checkin (@ganasai) and another one (@inspire99) to do the pull request. I am not sure, but this might cause problems for you perhaps in the review of Hacktoberfest. So I suggest maybe close this and do a new pull request with both commit and pull from the same user. 😄 

On another note, I noticed that the [Travis Build related to the commit](https://travis-ci.org/python-sinhala-education-society/OpenLearnr/builds/601375552?utm_source=github_status&utm_medium=notification) has some test failures. Can you correct that too?

**Comment by inspire99** [comment]
Hi @SudharakaP ,

Please check latest build passing pull request here --> https://github.com/python-sinhala-education-society/OpenLearnr/pull/160

Best regards
Ganesh

**Comment by SudharakaP** [comment]
@inspire99 : Thanks much for your first contribution to the repository. It looks great. I've merged it off. 😄
