### ISSUE TITLE
Improve SonarQube Grade

### ISSUE THREAD

**Issue by SudharakaP** [python-sinhala-education-society/OpenLearnr#163]
**Describe the bug**
Due to recent changes SonarQube is failing; https://sonarcloud.io/dashboard?id=com.asanka.tutor%3Aopen-learnr

**Expected behavior**
Need to have a passing SonarQube grade :smile:

**Comment by inspire99** [comment]
Yes, :) due to recent changes, for example, Video & VideoDTO has similar fields, it shows a duplicate finding in SonarQube. Let me check it.

**Comment by SudharakaP** [comment]
@inspire99 : Thanks :smile:

**Comment by inspire99** [comment]
Nice
