### ISSUE TITLE
Address all Warnings

### ISSUE THREAD

**Issue by SudharakaP** [python-sinhala-education-society/OpenLearnr#36]
**Describe the bug**
Address or minimize all compiler warnings. 

**Additional context**
https://bestpractices.coreinfrastructure.org/en/projects/2975

**Comment by inspire99** [comment]
@SudharakaP , the link provided in additional context - does not exist anymore.

**Comment by SudharakaP** [comment]
@inspire99 : Sorry the link has changed. I updated the link; https://bestpractices.coreinfrastructure.org/en/projects/2975. Please try now and let me know if you see any issues 😄

**Comment by SudharakaP** [comment]
This issue was created at a time when we had lots of compiler warning and stuff; I don't think this is now relevant; therefore closing this issue.

**Comment by inspire99** [comment]
@SudharakaP ok
