### ISSUE TITLE
Comment replies cannot approved

### ISSUE THREAD

**Issue by asanka-herath** [python-sinhala-education-society/OpenLearnr#50]
There is no option to approve the reply for a comment. when clicked on the reply it shows as approved. but when page refreshed the reply is unapproved and does not show in front end.

**Comment by SudharakaP** [comment]
@asanka-herath : Currently the comment reply needs to be approved as well (in addition to the comment). I've done that for the comment and below is a screen-cast of the approval process. 

![#50](https://user-images.githubusercontent.com/12435965/61840989-f81be700-ae47-11e9-8fba-e71710be5f8a.gif)

Let me know if this is not what you are looking for.
