### ISSUE TITLE
Add video name instead of video id in the comments entity screen

### ISSUE THREAD

**Issue by SudharakaP** [python-sinhala-education-society/OpenLearnr#51]
**Is your feature request related to a problem? Please describe.**
Currently when a comment is added to a video the admin has to find that video by ID; this is unnecessary. We could just add the video name (with a hyperlink) to the comment entity screen. 

**Describe the solution you'd like**
Remove Video ID column and add Video Name column with a link to the video.

![image](https://user-images.githubusercontent.com/12435965/61841447-9fe5e480-ae49-11e9-8626-e8052ddb0634.png)

**Comment by inspire99** [comment]
Hi @SudharakaP ,
I shall work on this.

Best Regards
Ganesh

**Comment by SudharakaP** [comment]
@inspire99 : Thanks much for the work you've done. I've went ahead and merged it.
