### ISSUE TITLE
Add support for search videos and chapter entity screens

### ISSUE THREAD

**Issue by SudharakaP** [python-sinhala-education-society/OpenLearnr#76]
**Is your feature request related to a problem? Please describe.**
We need a search bar for videos and chapter entity screens as well; similar to the one we implemented for user management section; #74 

**Describe the solution you'd like**
A similar search bar for user management section; I would say as a starting point this should filter based on the video name and chapter name.

**Comment by SudharakaP** [comment]
@coma123 : Hi, just checking; do you by any chance want to do this as well?

**Comment by coma123** [comment]
Hi, @SudharakaP 
Did not have time until now.
Please check https://github.com/python-sinhala-education-society/OpenLearnr/pull/78

**Comment by SudharakaP** [comment]
@coma123 : I think you haven't updated your develop branch and the pull request seems to revert certain changes that happened in the develop branch. 

Could you please use the following approach in making the changes. 

1) Sync your forks develop branch with the upstream develop branch; https://help.github.com/en/articles/syncing-a-fork . This will make sure your fork is in sync with the develop branch in ```python-sinhala-education-society/OpenLearnr``` repository.

2) Normally it's good practice to create a separate branch for each issue you work on in any project. [Create a new branch](https://www.youtube.com/watch?v=pDmYNK68IEc) (name it appropriately) and make all your changes there. 

3) Create a pull request from that branch. 

This strategy, done correctly will be helpful in any open source project you contribute to. If you have any questions let me know; I can help you out with the details. :smile: 

On another note; you might know that this project is scaffolded using the [Jhipster generator](https://github.com/jhipster/generator-jhipster). And it seems that this filtering logic is not implemented there as well; so after this change is done; if you are willing, I can help you out to create a PR to add that to the generator itself so that all new jhipster applications generated will have the filter by default (for the management screen). :smile:

**Comment by coma123** [comment]
@SudharakaP  thanks mate for correction, appreciate it. 👍 
I think that already did it good. Fetched it from origin, created branch and commited changes.
Please check https://github.com/python-sinhala-education-society/OpenLearnr/pull/80
If there is anything more feel free to tell me.
Thanks again for help

**Comment by SudharakaP** [comment]
@coma123 : Sorry about the Sonar issue; I just pushed some changes that will disable Sonar for pull requests as I thought it isn't strictly necessary anyways. 

Please update your fork from upstream. Now the new PR you've opened; I think you've created that new branch from the branch `sonar-coverage-enhancement` which I was working on (and contains some partial changes). Whenever you create a new branch you should create it from develop since that is the default branch for development. If you go to your new PR under the commits tab (https://github.com/python-sinhala-education-society/OpenLearnr/pull/81/commits) you'll not only see your new commits but also my commits from that `sonar-coverage-enhancement` branch. So I would suggest; 

1) Make sure your fork is upto date (as I've described previously)

2) Checkout develop branch. 

3) Then create a new branch (from develop) and add your changes there. 

4) Create a pull request (and when you go to your commit tab in the pull request you'll see only your commits; then you know only your commits will be merged not some other peoples commits).

Thank you. :smile:

**Comment by coma123** [comment]
@SudharakaP sorry for so many changes.
Merged to your branch, because wanted to solve sonar error. 😄 
Anyways, did it again with new branch in develop and made PR. I think that did it finally with good way 😄 
Thank you so much for your suggestions 👏 👍

**Comment by SudharakaP** [comment]
@coma123 : Thanks much for the contribution. Seems good. I'll do some testing in the evening. 👍

**Comment by SudharakaP** [comment]
@coma123 : I've tested and merged this. :+1: Thanks again for the work :+1:

**Comment by coma123** [comment]
@SudharakaP thanks to you for helping. 👍

**Comment by coma123** [comment]
Hi @SudharakaP,
If you can help me create PR to JHipster as you said, I will contribute there too making user search by default.

**Comment by SudharakaP** [comment]
@coma123 : It's not a difficult change; but the process might be a bit long; 

Firstly I think you took the filter bar from the [configuration.component.html](https://github.com/python-sinhala-education-society/OpenLearnr/blob/9370ed18d2ddd3bb63fd3bab14b70566be1f552f/src/main/webapp/app/admin/configuration/configuration.component.html#L6) (correct me if I am wrong). As you might know this file was auto generated from the [Jhipster generator](https://github.com/jhipster/generator-jhipster). Jhipster is a [Yeoman generator](https://yeoman.io/generators/) under the hood. Thus each file generated corresponds to a .ejs file; (https://ejs.co/). 

 The relevant .ejs file that generate this file is; [configuration.component.html.ejs](https://github.com/jhipster/generator-jhipster/blob/900e1f36ec5efac90a22d545a30943ae083742b1/generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.html.ejs#L22). Also to define the filter you need to change [configuration.component.ts.ejs](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/admin/configuration/configuration.component.ts.ejs) to define the filter logic. After this probably we need to add or modify [configuration.component.spec.ts.ejs](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/test/javascript/spec/app/admin/configuration/configuration.component.spec.ts.ejs) for the testing part as well. This is basically the summary of changes you need to do. 

In order to do them first you need to open a Issue (https://github.com/jhipster/generator-jhipster/issues). Then you need to to write down the the issue along with the changes you are gonna do. 

The process of submitting the changes can be found in their [CONTRIBUTING.md](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) along with the way you have to fork and setup the dev environment as well as the process of submitting a PR. If you follow that document carefully there won't be any issues. 

Let me know if you have any questions.

**Comment by coma123** [comment]
@SudharakaP Thanks for explaining.
As you said seems not big change but long process.
Yes I took it from [configuration.component.html](https://github.com/python-sinhala-education-society/OpenLearnr/blob/9370ed18d2ddd3bb63fd3bab14b70566be1f552f/src/main/webapp/app/admin/configuration/configuration.component.html#L6)
Ok, will take a look more deep in that files and try to fix it.

**Comment by SudharakaP** [comment]
Yes, let me know if you have any questions. I have been contributing to
Jhipster so I've done this process a lot of times. I can also create the
issue for you if you'd like?

**Comment by coma123** [comment]
@SudharakaP thanks, will appreciate if you can do it

**Comment by SudharakaP** [comment]
@coma123 : Just to be clear, you mean I create the issue and you do the pull request ? Or do you want me to do the pull request as well ?

**Comment by coma123** [comment]
@SudharakaP nah, thanks
will try to do all by myself, and if I don't understand something or need help will ask you if you don't mind

**Comment by SudharakaP** [comment]
@coma123 : Did you check out the addition to Jhipster by any chance? Just checking; you can take your time if you are working on it; let me know if you need any help 😄

**Comment by coma123** [comment]
Hey @SudharakaP . No I did not do it. Couldn't find time to sit down because of work. WIll try to do it.
Thanks for support and offering help 👍 😃
